

spring:
  application:
    name: huiyi
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/huiyi
    username: postgres
    password: sa123
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: true
#    view:
#      suffix: .html
#    static-path-pattern: /**
#  web:
#    resources:
#      static-locations: classpath:/templates/,classpath:/static/
#  thymeleaf:
#    enabled: true
#    encoding: utf-8
#    prefix: classpath:/templates/
#    suffix: .html
#    cache: false
#    mode: HTML
#    servlet:
#      content-type: text/html
#      chain:
#        strategy:
#          content:
#            enabled: true
#            paths: "/**"
logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
  file:
    name: HuiYi.log
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz
      max-file-size: 10MB
      max-history: 365
      total-size-cap: 1GB
server:
  port: 8888


